version: "3.9"

services:
  backend:
    build:
      context: ./prep-saga-backend
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db

  frontend:
    build:
      context: ./prep-saga-ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8082

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prepsaga
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
